# Generated by Django 6.0.6 on 2026-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_number', models.CharField(max_length=50, unique=True)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Store_location', models.CharField(db_index=True, max_length=100)),
                ('od_sphere', models.DecimalField(decimal_places=2, max_digits=4)),
                ('od_cylinder', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('os_sphere', models.DecimalField(decimal_places=2, max_digits=4)),
                ('os_cylinder', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('lens_type', models.CharField(choices=[('SINGLE_VISION', 'single vision'), ('BIFOCAL', 'Bifocal'), ('PROGRESSIVE', 'progressive')], db_index=True, max_length=100)),
                ('lens_index', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coating', models.CharField(max_length=100)),
                ('frame_model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PLACED', 'Order placed'), ('LAB_ROUTING', 'Lab Routing'), ('PROCESSING', 'Lens processing'), ('QC', 'Quality Check'), ('READY', 'Ready to Dispatch'), ('DELIVERED', 'Delivered')], db_index=True, default='PLACED', max_length=50)),
                ('inventory_source', models.CharField(blank=True, choices=[('IN_HOUSE', 'In House'), ('OUTSOURCED', 'Outsourced')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_hours', models.IntegerField(default=48)),
                ('predicted_tat_hours', models.FloatField(blank=True, null=True)),
                ('ai_breach_risk', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH_RISK', 'High Risk'), ('BREACHED', 'Breached')], default='NORMAL', max_length=20)),
            ],
        ),
    ]
